### ISSUE TITLE
Gray screen 

### ISSUE THREAD

**Issue by BalorSmooth** [imjangkar/albibong#14]
Hey, 

Once I started albibong from cmd I got these messages: 

Thread sniffer started
Thread packet_handler started
Thread ws_server started
Thread http_server started at port 54688

Albibong started but there ws nothing except a gray background. 
I'm using windows 11, python 3.10.11 

Anything I could do to solve this? 
![obraz_2024-07-30_121533860](https://github.com/user-attachments/assets/1852cb60-968e-4c4d-85e4-e62ad0f9d1ff)

**Comment by imjangkar** [comment]
hello, can you tell me what albibong version did you install?

**Comment by BalorSmooth** [comment]
Hello, I have 1.0.7. 
Didn't have problem to install it on my other pc. 

Correction, I have windows 10. (typo)

**Comment by imjangkar** [comment]
Can you try run Albibong again? And look for this message: `Thread http_server started at port XXXX`

Then open your browser and visit `localhost:XXXX` (XXXX is the port number in the message)

Let me know if the gray background persisted in the browser or not

**Comment by BalorSmooth** [comment]
Gray background on the browser. So it seems like it loaded but I have only a gray background. (I used Opera and Edge)

**Comment by imjangkar** [comment]
Hello, sorry for the very long wait. The issue has been solved in the latest update (ver 1.1.1). Please do check it out if you're still interested!

The problem (if you're interested):
A javascript application has to explicitly define MIME type to work on a Windows machine :(
